# enums
enum GroupRole {
    OWNER
    ADMIN
    SELECTOR
    PLAYER
}

enum PrimaryPosition {
    GK,
    DEF,
    MID,
    ATT
}

enum MatchType {
    INTERNAL
    MIXED_EXTERNAL
    TEAM_EXTERNAL
}

enum Team {
    TEAM_A
    TEAM_B
}

# types
type DemoPlayer {
    id: ID!
    name: String!
    speedRank: Int
    techniqueRank: Int
    primaryPosition: String
}

type Pitch {
    id: ID!
    name: String!
    city: String!
}

type MatchParticipation {
    playerId: ID!
    team: Team!
    goals: Int!
    assists: Int!
    playedAsGoalkeeper: Boolean
    isMvp: Boolean
}

type Match {
    id: ID!
    matchDate: String!
    matchType: MatchType!
    pitch: Pitch
    teamAScore: Int
    teamBScore: Int
    participations: [MatchParticipation!]!
}

type Player {
    id: ID!
    firstName: String!
    lastName: String
    nickName: String
    birthYear: Int

    speedRank: Int
    techniqueRank: Int
    defenseSkillRank: Int
    defenseWorkRate: Int
    stamina: Int

    primaryPosition: PrimaryPosition

    canPlayAsGk: Boolean!
    isGoalkeeperToday: Boolean!
    isAdmin: Boolean!
    isCoach: Boolean!

    user: User
    group: Group!

    joinedAt: String
}

type User {
    id: ID!
    keycloakId: String!
    email: String!
    createdAt: String
    ownedGroups: [Group!]!
    players: [Player!]!
}

type Group {
    id: ID!
    name: String
    owner: User!
    createdAt: String
    players: [Player!]!
}

# inputs
input PlayerSaveInput {
    firstName: String!
    lastName: String
    nickName: String
    birthYear: Int
    primaryPosition: PrimaryPosition
    groupId: ID!
}

input ParticipationSaveInput {
    playerId: ID!
    team: Team!
    goals: Int
    assists: Int
    playedAsGoalkeeper: Boolean
}

input MatchSaveInput {
    matchDate: String!
    matchType: MatchType!
    pitchId: ID!
}

input MatchUpdateInput {
    matchDate: String
    matchType: MatchType
    pitchId: ID
    teamAScore: Int
    teamBScore: Int
    participations: [ParticipationSaveInput!]
}


# operations
type Query {
    getDemoPlayers: [DemoPlayer!]!
    getPlayers: [Player!]!
    getPlayerById(id: ID!): Player
    getMatch(id: ID!): Match
    # logged user
    me: User
    getGroup(id: ID!): Group
    # logged user groups
    myGroups: [Group!]!
}

type Mutation {
    createMatch(groupId: ID!, matchData: MatchSaveInput!): Match!
    updateMatch(matchId: ID!, input: MatchUpdateInput!): Match!
}