CREATE TABLE users
(
    id          BIGSERIAL PRIMARY KEY,
    keycloak_id VARCHAR(255)              NOT NULL UNIQUE,
    email       VARCHAR(255)              NOT NULL UNIQUE,
    created_at  DATE DEFAULT CURRENT_DATE NOT NULL
);

CREATE TABLE groups
(
    id         BIGSERIAL PRIMARY KEY,
    name       VARCHAR(100),
    owner_id   BIGINT                    NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE NOT NULL,

    CONSTRAINT fk_groups_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE players
(
    id                  BIGSERIAL PRIMARY KEY,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100),
    nick_name           VARCHAR(100),
    birth_year          INT,
    speed_rank          INT,
    technique_rank      INT,
    defense_skill_rank  INT,
    defense_work_rate   INT,
    stamina             INT,
    primary_position    VARCHAR(50),
    can_play_as_gk      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_goalkeeper_today BOOLEAN      NOT NULL DEFAULT FALSE,
    is_admin            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_coach            BOOLEAN      NOT NULL DEFAULT FALSE,
    user_id             BIGINT,
    group_id            BIGINT       NOT NULL,
    joined_at           DATE,

    CONSTRAINT fk_players_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_players_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_group UNIQUE (user_id, group_id)
);

CREATE TABLE invitations
(
    code        UUID PRIMARY KEY,
    group_id    BIGINT                   NOT NULL,
    player_name VARCHAR(100)             NOT NULL,
    status      VARCHAR(20)              NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE pitches
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    city          VARCHAR(255) NOT NULL,
    street        VARCHAR(127),
    street_number INT
);

CREATE TABLE matches
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_date   TIMESTAMP   NOT NULL,
    match_type   VARCHAR(50) NOT NULL,
    team_a_score INT,
    team_b_score INT,
    group_id     BIGINT      NOT NULL,
    pitch_id     BIGINT,
    CONSTRAINT fk_match_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_match_pitch FOREIGN KEY (pitch_id) REFERENCES pitches (id)
);

CREATE TABLE match_participations
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id             BIGINT      NOT NULL,
    player_id            BIGINT, -- nullable if we want to have outer players
    team                 VARCHAR(20) NOT NULL,
    goals                INT         NOT NULL DEFAULT 0,
    assists              INT         NOT NULL DEFAULT 0,
    played_as_goalkeeper BOOLEAN     NOT NULL DEFAULT FALSE,
    is_mvp               BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_participation_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
    CONSTRAINT fk_participation_player FOREIGN KEY (player_id) REFERENCES players (id)
);

CREATE INDEX idx_matches_group_id ON matches (group_id);
CREATE INDEX idx_match_participations_match_id ON match_participations (match_id);
CREATE INDEX idx_match_participations_player_id ON match_participations (player_id);